version: "3.3"

services:
  vault:
    image: vault
    command: server -dev
    cap_add:
      - IPC_LOCK
    environment:
      - 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    volumes:
      - ./data/vault/logs:/vault/logs
      - ./data/vault/file:/vault/file
      - ./data/vault/config:/vault/config
    ports:
      - 8200:8200

